title: Mind & Motion at UIST 2025
description: Workshop on Opportunities and Applications of Integrating Biomechanics and Cognitive Models in HCI
show_downloads: true
google_analytics: G-8BL0XYF2HZ
theme: jekyll-theme-cayman