title: Mind & Motion at CHI 2025
description: Workshop on Opportunities and Applications of Integrating Biomechanics and Cognitive Models in UI Design
show_downloads: false
google_analytics: G-8BL0XYF2HZ
theme: jekyll-theme-cayman