title: Mind & Motion Opportunities and Applications of Integrating Biomechanics and Cognitive Models in UI Design
description: Workshop at CHI 2025
show_downloads: false
google_analytics: G-8BL0XYF2HZ
theme: jekyll-theme-cayman